name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  - ipywidgets
  - pydantic-core
  - pydantic>=2
  # Other useful libraries for LLMs
  - numpy
  - pip
  - pip:
    - llm 
    - openai
    - google-genai
	- llm-anthropic
	- llm-gemini
