name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - pydantic-core
  - pydantic>=2
  - numpy
  - llm
  - openai
  - google-genai
